# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Cotorra
name: Cotorra ChatBot
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://cotorrachatbot.com" # the base hostname & protocol for your site
#url: "http://localhost:4000" # the base hostname & protocol for your site
description: Cotorra es un chatbot, robot chat, un bot para Facebook Meseenger, funciona como un asistente automatizado para su negocio.
keywords: chatbot, robot chat, bot, messenger, bot messenger, bot facebook, robot facebook
favicon: img/favicon.png
image: img/cotorrachatbot-banner.png
permalink: /:title


#Adsense code
adsense:

#Site Stats
google_analytics: UA-1336963-15

#Google Search console Verification
searchconsole_verification: Cz9uWeg0JBlw700cGc_Dq6O5lpWBl7k-LUA4Ww92NTI

#Bing Webmaster tools Verification
bing_verification:


#Comments
disqus:

#Facebook
#App ID
facebook_app: 1243750798976697
facebook_adminid:

socialmedia:
  facebook: cotorrachatbot
  twitter: cotorrachatbot
  googleplus:
  instagram: cotorrachatbot
  youtube: UCSbE9uxH9A9by0z7Tuf8uFw


# Build settings
markdown: kramdown

#
include:
 - _pages
