# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Cotorra
name: Cotorra ChatBot
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://cotorrachatbot.com" # the base hostname & protocol for your site
description: Cotorra es un chatbot, robot chat, un bot para Facebook Meseenger, funciona como un asistente automatizado para su negocio.
keywords: chatbot, robot chat, bot, messenger, bot messenger, bot facebook, robot facebook
favicon: img/favicon.png
image: img/jekyll-start.png
permalink: /:title


#Adsense code
adsense:

#Site Stats
google_analytics:

#Google Search console Verification
searchconsole_verification:

#Bing Webmaster tools Verification
bing_verification:


#Comments
disqus:

#Facebook
#App ID
facebook_app:
facebook_adminid:

socialmedia:
  facebook: cotorrachatbot
  twitter:
  googleplus:
  instagram:
  youtube:


# Build settings
markdown: kramdown

#
include:
 - _pages
